### ISSUE TITLE
Menubar with Toolbar?

### ISSUE THREAD

**Issue by latenitefilms** [asmagill/hs._asm.guitk#3]
I have no idea how it would work technically, but I'd love to be able to do something like this:

![image](https://user-images.githubusercontent.com/22286696/166167844-6d23d47a-e40a-4323-87f7-977346bccbd3.png)

**Comment by asmagill** [comment]
As a "close fake", you could make the menubar item invoke a callback that drew a canvas which then did a pop-up menu based on which area within the canvas you moved to/clicked in.

As to the "proper" way to do it with menuitems as proper NSViews with their own elements... that's something I envision being possible with the GUI toolkit I was talking about a couple of years ago... it's still on my radar, just kinda been pushed to the back because of life and other issues.  The rewrite of menubar I mentioned in a recent thread would be part of this shift to a more expressive view oriented approach to all visual elements, so that's probably where I'll start, though being able to stick a toolbar/canvas view into a menu item will likely not be part of the first iteration... the first iteration will be to make sure we have at least parity with the current menubar before we completely replace it.

**Comment by asmagill** [comment]
Closing; uitk.menubar should be able to do this, though it's still in very early stages...
